// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Usage struct {
	UsageID           int32
	Type              string
	Duration          int32
	Spotperkwh        pgtype.Numeric
	Perkwh            pgtype.Numeric
	Kwh               pgtype.Numeric
	Cost              pgtype.Numeric
	Date              pgtype.Date
	Nemtime           pgtype.Timestamptz
	Starttime         pgtype.Timestamptz
	Endtime           pgtype.Timestamptz
	Renewables        pgtype.Numeric
	Channeltype       string
	Channelidentifier string
	Spikestatus       string
	Descriptor        string
	Quality           string
	Tariffinformation []byte
	Demandwindow      bool
}
